sudo: false
install: true

language: java

arch:
  - amd64
os:
  - linux
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "sonarcloud-marc7806"
    token: ${SONAR_TOKEN}

before_install:
  - sudo add-apt-repository -y ppa:chris-needham/ppa
  - sudo apt-get -q update
  - sudo apt-get -y install audiowaveform

script:
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=sonarcloud-marc7806 -DAWF_PATH=/usr/bin/audiowaveform

cache:
  apt: true
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'